name: Pysa

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Upload SARIF Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: sarif.json
